schoolstore/school/schoolproject/schoolapp/urls.py
from django .urls import path
from .import views
app_name='schoolapp'

urlpatterns=[
    path('',views.allProCat,name="allProCat"),
    path('<slug:c_slug>/', views.allProCat, name="products_by_category"),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name="ProdutCategoryDetail"),
    path('cse',views.cse,name="cse"),
    path('ce',views.ce,name="ce"),
    path('me',views.me,name="me"),
    path('ece',views.ece,name="ece"),
    path('eee',views.eee,name="eee"),
    path('register',views.register,name="register"),
    path('login',views.login,name="login"),
    path('form', views.form, name="form"),
    path('forms', views.forms, name="forms"),

]

schoolstore/school/schoolproject/schoolproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('schoolapp.urls')),
    path('search/',include('searchapp.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

schoolstore/school/schoolproject/searchapp/urls.py
from django.urls import path
from . import views


app_name='searchapp'
urlpatterns=[
    path('',views.SearchResult,name='SearchResult'),
]

schoolstore/school/schoolproject/schoolapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=100,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'



    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        return reverse('schoolapp:products_by_category', args=[self.slug])

class Product(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='product', blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('schoolapp:ProdutCategoryDetail',args=[self.category.slug,self.slug])
    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

schoolstore/school/schoolproject/searchapp/models.py
from django.db import models

# Create your models here.

schoolstore/school/schoolproject/schoolapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect

from schoolapp.models import Category,Product


# Create your views here.
def allProCat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug != None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list = Product.objects.all().filter(available=True)

    return render(request, "category.html", {'category': c_page, 'products': products_list})


def proDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except  Exception as e:
        raise e
    return render(request,"product.html",{'product':product})

def cse(request):
    return render(request,"cse.html")

def ce(request):
    return render(request,"ce.html")

def me(request):
    return render(request,"me.html")

def ece(request):
    return render(request,"ece.html")

def eee(request):
    return render(request,"eee.html")


def register(request):
    if request.method=='POST':
        username=request.POST['Username']
        password = request.POST['Password']
        password1 = request.POST['Conform password']
        if password==password1:
            if User.objects.filter(username=username).exists():
                messages.info(request,"Username Taken")
                return redirect('schoolapp:register')
            else:
                user=User.objects.create_user(username=username,password=password)

                user.save();
                return redirect('schoolapp:login')


        else:
            messages.info(request, "Password not matching")
            return redirect('register')


    return render(request,"register.html")


def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('schoolapp:form')
        else:
            messages.info(request,"invalid username or password")
            return redirect('schoolapp:login')
    return render(request, "login.html")

def form(request):
    return redirect('schoolapp:forms')
    return render(request,'form.html')

def forms(request):
    return render(request,'forms.html')

schoolstore/school/schoolproject/searchapp/views.py
from django.shortcuts import render
from schoolapp.models import Product
from django.db.models import Q
# Create your views here.


def SearchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request,'search.html',{'query':query,'products':products})

# Create your views here.

schoolstore/school/schoolproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <link rel="stylesheet" href="{% static 'css/coustom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>

<div class="container">
{% include 'nav.html' %}
{% block content %}
{% endblock %}
{% include 'footer.html' %}
</div>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<script src=" https://code.jquery.com/jquery-3.2.1.slim.min.js " integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src=" https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js " integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src=" https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js " integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

schoolstore/school/schoolproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to our school Store where you can Enjoy your Shopping....
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }} - School Store
    {% else %}
        See your amazing shoping
    {% endif %}
{% endblock %}
{% block content %}
{% if category %}
    <div>
        <div class="row my_row_class">
            <div class="mx_auto">
               <p><a href="{% url 'schoolapp:allProCat' %}">Our Product Collection</a></p>
            </div>

        </div>
    </div>
{% endif %}
 <div class="mx_auto">
    {% if category %}
    <img src="{{ category.image.url }}" alt="{{ category.name }}"width="1100" height="300">
        </div>
        <br>
        <div>
        <h1 class="text-center my_title">{{ category.name }}</h1>
        <p class="text-justify">{{ category.description }}</p>
    </div>
    {% else %}
    <div>
    <img class="my_image my_image_padding" src="{% static 'img/school.jpg' %}" alt="our products" width="1600px;" height="500px;">
    </div>
            <br>
    <div>
    <h1 class="text-center my_title"> Our Collection</h1>
    <p class="text_justify">It helps the designer plan where the content will sit. It helps in creating drafts of the content on the pages of the website. It originates from the Latin text but is seen as gibberish.

Sometimes, the reader gets distracted while creating or working on the website. That’s why this language is important.This tool makes the work easier for the webmaster.</p>
    </div>
    {% endif %}

    <div class="container">
         <div class="row mx_auto">
             {% for product in products %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4" >
                <div class="card text-center" style="">
                        <a href="{{ product.get_url }}"><img  src="{{ product.image.url }}" alt="{{product.name}}" width="340px;" height="200px;"></a>
                    <div class="card-body">
                          <h4>{{ product.name }}</h4>
                        <p>{{ product.price }}</p>
                    </div>
                 </div>
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

schoolstore/school/schoolproject/templates/ce.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="super_container">

	<!-- Header -->

	<header class="header">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-start">
						<div class="header_content_inner d-flex flex-row align-items-end justify-content-start">
                            <div class="logo"><h1>COMMERCE DEPARTMENT</h1></div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <div class="header_phone ml-auto">Call us: 00-56 445 678 33</div>
                            <div class="hamburger ml-auto">
								<i class="fa fa-bars" aria-hidden="true"></i>
							</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="menu">
		<div class="menu_header d-flex flex-row align-items-center justify-content-start">

			<div class="menu_close_container ml-auto"><div class="menu_close"><div></div><div></div></div></div>
		</div>
<div>
    <img src="static/img/com.jpeg" alt="dummy" style="width:1100px; height:350px;">
</div>
        <div>
    <h1 class="text-center my_title"> About Department</h1>
    <p class="text_justify">It helps the designer plan where the content will sit. It helps in creating drafts of the content on the pages of the website. It originates from the Latin text but is seen as gibberish.

Sometimes, the reader gets distracted while creating or working on the website. That’s why this language is important.This tool makes the work easier for the webmaster.</p>
    </div>
</div>
</div>
{% endblock %}

schoolstore/school/schoolproject/templates/cse.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="super_container">

	<!-- Header -->

	<header class="header">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-start">
						<div class="header_content_inner d-flex flex-row align-items-end justify-content-start">
                            <div class="logo"><h1>ENGINEERING DEPARTMENT</h1></div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <div class="header_phone ml-auto">Call us: 00-56 445 678 33</div>
                            <div class="hamburger ml-auto">
								<i class="fa fa-bars" aria-hidden="true"></i>
							</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="menu">
		<div class="menu_header d-flex flex-row align-items-center justify-content-start">
			<div class="menu_close_container ml-auto"><div class="menu_close"><div></div><div></div></div></div>
		</div>
        <div>
            <img src="static/img/eng.jpg" alt="dummy" style="width:1100px; height:350px;">
        </div>
        <div>
            <h1 class="text-center my_title"> About Department</h1>

                <p class="text-justify">It helps the designer plan where the content will sit. It helps in creating drafts of the content on the pages of the website. It originates from the Latin text but is seen as gibberish.

                Sometimes, the reader gets distracted while creating or working on the website. That’s why this language is important.This tool makes the work easier for the webmaster.It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
        </div>
    </div>
</div>
{% endblock %}

schoolstore/school/schoolproject/templates/ece.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="super_container">

	<!-- Header -->

	<header class="header">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-start">
						<div class="header_content_inner d-flex flex-row align-items-end justify-content-start">
                            <div class="logo"><h1>CHEMISTRY DEPARTMENT</h1></div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <div class="header_phone ml-auto">Call us: 00-56 445 678 33</div>
                            <div class="hamburger ml-auto">
								<i class="fa fa-bars" aria-hidden="true"></i>
							</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </header>
    <div class="menu">
		<div class="menu_header d-flex flex-row align-items-center justify-content-start">
			<div class="menu_close_container ml-auto"><div class="menu_close"><div></div><div></div></div></div>
		</div>
<div>
    <img src="static/img/chemistry.png" alt="dummy" style="width:1100px; height:350px;">
</div>
        <div>
    <h1 class="text-center my_title"> About Department</h1>
    <p class="text_justify">It helps the designer plan where the content will sit. It helps in creating drafts of the content on the pages of the website. It originates from the Latin text but is seen as gibberish.

    Sometimes,the reader gets distracted while creating or working on the website. That’s why this language is important.This tool makes the work easier for the webmaster.</p>
    </div>
</div>
</div>
{% endblock %}

schoolstore/school/schoolproject/templates/eee.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="super_container">

	<!-- Header -->

	<header class="header">
		<div class="container">
			<div class="row">
				<div class="col">
					<div class="header_content d-flex flex-row align-items-center justify-content-start">
						<div class="header_content_inner d-flex flex-row align-items-end justify-content-start">
                            <div class="logo"><h1>MATHEMATICS DEPARTMENT</h1></div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <div class="header_phone ml-auto">Call us: 00-56 445 678 33</div>
                            <div class="hamburger ml-auto">
								<i class="fa fa-bars" aria-hidden="true"></i>
							</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </header>
    <div class="menu">
		<div class="menu_header d-flex flex-row align-items-center justify-content-start">

			<div class="menu_close_container ml-auto"><div class="menu_close"><div></div><div></div></div></div>
		</div>
<div>
    <img src="static/img/math.png" alt="dummy" style="width:1100px; height:350px;">
</div>
        <div>
    <h1 class="text-center my_title"> About Department</h1>
    <p class="text_justify">It helps the designer plan where the content will sit. It helps in creating drafts of the content on the pages of the website. It originates from the Latin text but is seen as gibberish.

Sometimes, the reader gets distracted while creating or working on the website. That’s why this language is important.This tool makes the work easier for the webmaster.</p>
    </div>
</div>
</div>
{% endblock %}

schoolstore/school/schoolproject/templates/footer.html
<footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2023 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">SchoolStore.com</a>
  </div>
  <!-- Copyright -->
</footer>

schoolstore/school/schoolproject/templates/form.html
<!DOCTYPE html>
<html>
<head>
     <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action="#">
{% csrf_token %}
    <button type="button">Click Me!</button>
</form>
</body>
</html>

schoolstore/school/schoolproject/templates/forms.html
<html>
  <head>
    <meta charset="utf-8">
    <title>Form</title>
    <link href="static/css/other.css" type="text/css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <!-- Body of Form starts -->
  	<div class="container">
      <form method="post" autocomplete="on">
          {% csrf_token %}
        <!--First name-->
    		<div class="box">
          <label for="firstName" class="fl fontLabel">  Name: </label>
    			<div class="new iconBox">
            <i class="fa fa-user" aria-hidden="true"></i>
          </div>
    			<div class="fr">
    					<input type="text" name="firstName" placeholder=" Name"
              class="textBox" autofocus="on" required>
    			</div>
    			<div class="clr"></div>
    		</div>
    		<!--First name-->


       <div class="box">
          <label for="email" class="fl fontLabel"> Email ID: </label>
    			<div class="fl iconBox"><i class="fa fa-envelope" aria-hidden="true"></i></div>
    			<div class="fr">
    					<input type="email" required name="email" placeholder="Email Id" class="textBox">
    			</div>
    			<div class="clr"></div>
    		</div>
    		<!--Email ID----->

        <div class="box">
          <label for="dob" class="fl fontLabel"> DOB: </label>
    			<div class="fl iconBox"><i class="fa fa-calendar" aria-hidden="true"></i></div>
    			<div class="fr">
    					<input type="date" required name="dob" placeholder="DOB" class="textBox">
    			</div>
    			<div class="clr"></div>
    		</div>
    		<!--AGE----->
          <div class="box">
                <label for="age" class="fl fontLabel"> Age: </label>
    			<div class="fl iconBox"><i class="fa fa-user" aria-hidden="true"></i></div>
    			<div class="fr">
    					<input type="text" required name="age" maxlength="10" placeholder="Enter your age" class="textBox">
    			</div>
    			<div class="clr"></div>
    		</div>
    		<!---Phone No.------>
    		<div class="box">
          <label for="phone" class="fl fontLabel"> Phone No: </label>
    			<div class="fl iconBox"><i class="fa fa-phone-square" aria-hidden="true"></i></div>
    			<div class="fr">
    					<input type="text" required name="phoneNo" maxlength="10" placeholder="Phone No." class="textBox">
    			</div>
    			<div class="clr"></div>
    		</div>
    		<!---Phone No.---->


    		<!---Email ID---->
    		<div class="box">
          <label for="address" class="fl fontLabel"> Address: </label>
    			<div class="fl iconBox"><i class="fa fa-user" aria-hidden="true"></i></div>
    			<div class="fr">
    					<input type="text" required name="address" placeholder="Address" class="textBox">
    			</div>
    			<div class="clr"></div>
    		</div>

          <!---dept-->

<div class="box">
    <label for="country" class="fl fontLabel">Department:</label>
    <div class="fl iconBox"><i class="fa-caret-down" aria-hidden="true"></i></div>
     <div class="fr">
        <select id="country" class="textBox">
            <option value="">-- Select Department --</option>
            <option value="usa">Engineering</option>
            <option value="canada">Commerce</option>
            <option value="physics">Physics</option>
            <option value="chemistry">Chemistry</option>
            <option value="mathematics">Mathematics</option>
        </select>

    <br>
     </div>
</div>
 <div class="box">
    <label for="city" class="fl fontLabel">Course:</label>
     <div class="fl iconBox"><i class="fa fa-caret-down" aria-hidden="true"></i></div>
     <div class="fr">
         <select id="city" class="textBox">
            <option value="">-- Select Course --</option>
         </select>
     </div>
</div>
    <script>
        // Data for dependent dropdown options
        const citiesByCountry = {
            usa: ["CSE", "EEE", "ECE","ME","CE"],
            canada: ["B.com", "M.com", "CA"],
            physics: ["BA", "MA"],
            chemistry: ["BA", "MA"],
            mathematics: ["BA", "MA"]
        };

        // Get references to the select elements
        const countrySelect = document.getElementById("country");
        const citySelect = document.getElementById("city");

        // Event listener for the country dropdown
        countrySelect.addEventListener("change", function() {
            const selectedCountry = countrySelect.value;
            citySelect.innerHTML = ""; // Clear the city dropdown

            if (selectedCountry in citiesByCountry) {
                citiesByCountry[selectedCountry].forEach(function(city) {
                    const option = document.createElement("option");
                    option.value = city;
                    option.textContent = city;
                    citySelect.appendChild(option);
                });
            } else {
                const defaultOption = document.createElement("option");
                defaultOption.value = "";
                defaultOption.textContent = "-- Select City --";
                citySelect.appendChild(defaultOption);
            }
        });
    </script>




    		<!--Purpose----->
          <div class="box">
          <label id="purpose" class="fl fontLabel"> Purpose: </label>
             <div class="fl iconBox"><i class="fa fa-caret-down" aria-hidden="true"></i></div>
             <div class="fr">
                 <select id="dropdown"  name="purpose" required  class="textBox">
                     <option disabled selected value>
        Select
      </option>
                            <option value="enquiry">Enquiry</option>
                            <option value="placeorder">Place Order</option>
                            <option value="return">Return</option>
                </select>
             	</div>
    			<div class="clr"></div>
</div>
<!---dept--->


 <!----material-------------->

          <div class="box checkbox">
          <label for="material" class="fl fontLabel"> Material Provide : </label><br>
    				<input type="checkbox" id="notebook" name="notebook" value="Notebook">&nbsp;
                    <label for="notebook"> Notebook</label>
    				<input type="checkbox" id="pencil" name="pencil" value="Pencil">&nbsp;
                    <label for="pencil"> Pencil</label>
                    <input type="checkbox" id="exampaper" name="exampaper" value="Exam paper">&nbsp;
                    <label for="exampaper"> Exam paper</label><br>
                    <input type="checkbox" id="pen" name="pen" value="Pen">&nbsp;
                    <label for="pen">Pen</label>
                    <input type="checkbox" id="pen" name="paper" value="Paper">&nbsp;
                    <label for="paper"> Paper</label>
    		</div>



    		<!---gender------>
            <div class="box radio">
                 <label for="gender" class="fl fontLabel"> Gender: </label>
                <label>
                    <input type="radio" name="Gender" value="Male" required>
                </label> Male &nbsp; &nbsp; &nbsp; &nbsp;
                <label>
                    <input type="radio" name="Gender" value="Female" required>
                </label> Female&nbsp;&nbsp;&nbsp;
                <label>
                    <input type="radio" name="Gender" value="Other" required>
                </label> Other
    		</div>
<!----submit-->
          <div class="box" style="background: #2d3e3f">
            <input type="submit" class="submit" name= "submit" value="Submit" onclick="alert('Your Action is Completed!')">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <div  class="submit">
              <a href="{% url 'schoolapp:allProCat'%}" id="LogoutAction">Log out</a>
          </div>
          </div>



  <!--Body of Form ends--->
      </form>
    </div>
  </body>
</html>

schoolstore/school/schoolproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        {{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
    {% if category %}
        {{ product.name }} - Shopee Store

    {% endif %}
{% endblock %}

{% block content %}
<div class="row mt_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'schoolapp:allProCat' %}">Home</a> | <a href="{{ product.category.get_url }}">{{ product.category }}</a>| {{ product.name }}</p>
    </div>
</div>
<div class="container">
 <br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width:18rem">
                <img src="{{ product.image.url }}" alt="{{ product.name }}">
            </div>
        </div>
    <div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1 class="my_prod_title">{{ product.name }}</h1>
                <p>${{ product.price }}</p>
                <p class="my_title"> Product Description</p>
                <p class="text-justify my_prod_text">{{ product.description }}</p>
                {% if product.stock <= 0 %}
                <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
                {% endif %}
            </div>
        </div>
    </div>
    </div>
</div>
{% endblock %}